//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adjustment()
        {
            this.AdjustmentDetails = new HashSet<AdjustmentDetail>();
        }
    
        public string Voucher_ID { get; set; }
        public System.DateTime Issue_Date { get; set; }
        public Nullable<System.DateTime> Approved_Date { get; set; }
        public string IssuedByStaff_ID { get; set; }
        public string ApprovedByStaff_ID { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Staff Staff1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentDetail> AdjustmentDetails { get; set; }
    }
}
