//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdjustmentDetail
    {
        public string Voucher_ID { get; set; }
        public string Item_ID { get; set; }
        public int Adj_Qty { get; set; }
    
        public virtual Adjustment Adjustment { get; set; }
        public virtual Item Item { get; set; }
    }
}
