//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.AdjustmentDetails = new HashSet<AdjustmentDetail>();
            this.DisbursementDetails = new HashSet<DisbursementDetail>();
            this.ItemTransactions = new HashSet<ItemTransaction>();
            this.OrderListDetails = new HashSet<OrderListDetail>();
            this.RequisitionItems = new HashSet<RequisitionItem>();
            this.SupplierInventories = new HashSet<SupplierInventory>();
        }
    
        public string Item_ID { get; set; }
        public string Category_ID { get; set; }
        public string Item_Name { get; set; }
        public int Reorder_Level { get; set; }
        public int Reorder_Qty { get; set; }
        public string UOM { get; set; }
        public string Bin_ID { get; set; }
        public string FirstSupplier_ID { get; set; }
        public string SecondSupplier_ID { get; set; }
        public string ThirdSupplier_ID { get; set; }
        public int Inventory { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdjustmentDetail> AdjustmentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisbursementDetail> DisbursementDetails { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Supplier Supplier1 { get; set; }
        public virtual Supplier Supplier2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemTransaction> ItemTransactions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderListDetail> OrderListDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionItem> RequisitionItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierInventory> SupplierInventories { get; set; }
    }
}
