//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTransaction
    {
        public string Item_ID { get; set; }
        public System.DateTime Update_Date { get; set; }
        public string Reason { get; set; }
        public int Quantity { get; set; }
        public int Balance { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
