//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderListDetail
    {
        public string Order_ID { get; set; }
        public string Item_ID { get; set; }
        public int Needed_Qty { get; set; }
        public Nullable<int> Received_Qty { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual OrderList OrderList { get; set; }
    }
}
