//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderList()
        {
            this.OrderListDetails = new HashSet<OrderListDetail>();
        }
    
        public string Order_ID { get; set; }
        public string Supplier_ID { get; set; }
        public System.DateTime Create_Date { get; set; }
        public Nullable<System.DateTime> Finish_Date { get; set; }
        public string OrdStaff_ID { get; set; }
        public string RecStaff_ID { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderListDetail> OrderListDetails { get; set; }
        public virtual Staff OrdStaff { get; set; }
        public virtual Staff RecStaff { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
