//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requisition()
        {
            this.RequisitionItems = new HashSet<RequisitionItem>();
        }
    
        public string Requisition_ID { get; set; }
        public string SubmissionStaff_ID { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string ApprovedByStaff_ID { get; set; }
        public string RequisitonType { get; set; }
        public string Remark { get; set; }
        public string Disbursement_ID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    
        public virtual Disbursement Disbursement { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionItem> RequisitionItems { get; set; }
        public virtual Staff Staff1 { get; set; }
    }
}
